# Generated by Django 2.2.1 on 2019-09-22 17:51
import django.conf
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('django_keycloak_auth', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='RemoteUserOpenIdConnectProfile',
            name='is_service_account',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
