# Generated by Django 2.2.1 on 2019-09-25 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("keycloak_auth", "0002_remoteuseropenidconnectprofile_user")]

    operations = [
        migrations.AlterField(
            model_name="remoteuseropenidconnectprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oidc_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
