# Generated by Django 3.1.5 on 2021-02-24 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak_auth', '0003_next_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoutState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('next_path', models.TextField(null=True)),
            ],
        ),
    ]
